### ISSUE TITLE
train lgb

### ISSUE THREAD

**Issue by Jie-Yuan** [Azure/mmlspark#639]
ERROR org.apache.spark.executor.Executor: Exception occurred when executing task: Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)

**Comment by mhamilton723** [comment]
@imatiach-msft can help out here. I dont think thats the right section of the error message to diagnose

**Comment by imatiach-msft** [comment]
@Jie-Yuan sorry about the trouble you are having.  Are you still seeing this issue with mmlspark v0.18.1?  Also, do you have dynamic allocation disabled on your cluster?  This error usually occurs when the training is stuck.

**Comment by candalfigomoro** [comment]
@imatiach-msft 
I have a similar issue with a 800 columns x 5 million rows dataset. I keep getting "connection refused" or "connection reset" errors on fit. mmlspark v0.18.1 with dynamic allocation disabled. I also tried voting_parallel mode, batch training and stratified repartition. I keep getting those errors (a mix of connection refused and connection reset errors).

**Comment by candalfigomoro** [comment]
Another common error is "next on empty iterator", especially when I try to use batch training. I also tried to use generateMissingLabels=True

**Comment by candalfigomoro** [comment]
When I try to use barrier mode, I get this error:

"Barrier execution mode does not allow the following pattern of RDD chain within a barrier stage:
1. Ancestor RDDs that have different number of partitions from the resulting RDD (eg. union()/coalesce()/first()/take()/PartitionPruningRDD). A workaround for first()/take() can be barrierRdd.collect().head (scala) or barrierRdd.collect()[0] (python).
2. An RDD that depends on multiple barrier RDDs (eg. barrierRdd1.zip(barrierRdd2))."

**Comment by imatiach-msft** [comment]
@candalfigomoro sorry, barrier execution isn't working with 0.18.1, I just merged a fix for it to master this week - it will be in the next patch.  You can also use the latest build from master, but I'm not sure if that would fix your issue.  Are you doing binary classification or multiclass?  What does your label distribution look like?  How big is your cluster?

**Comment by candalfigomoro** [comment]
@imatiach-msft It's an unbalanced binary classification (about 1% of positives). I tried to use stratifed repartition (with mode='original' because with other modes such as "mixed" the size explodes) or generateMissingLabels=True, but I still get errors. 8 executors, 1 CPU / 16 GB of RAM per executor. At the moment I use undersampling + vanilla (non-distributed) LightGBM, I wanted to see if with mmlspark I could avoid undersampling the majority class.

**Comment by imatiach-msft** [comment]
Sorry about the trouble you are having.  That's one edge case where generateMissingLabels won't work for right now, but really that mode is more for debugging or a last resort.  Using stratified repartition should in theory work, but it is very new and there seem to be issues with it.  The issue is that there are some partitions with only one label, and in that case those workers exit early in the first iteration (you can see them in your cluster worker view with SUCCESS status), and the other workers get stuck waiting for them.  I think I need to:
1.) figure out why stratified repartition is not working for you and improve it
2.) file a bug in lightgbm repo for this unbalanced distributed scenario where the classifier gets stuck and see what they might suggest
You can try to figure out a way to make the classes balanced, but unfortunately this is something that still needs to be fixed.

**Comment by imatiach-msft** [comment]
@candalfigomoro FYI the issue with unbalanced labels was fixed in lightgbm native code, and latest master has the fix.  generateMissingLabels parameter has been removed.  There still seem to be issues with stratified repartition which I may need to revisit later on, but it shouldn't be needed for this scenario anymore.

**Comment by ranadeepsingh** [comment]
We are closing this issue as the underlying connection failure caused by unbalanced partition labels was fixed in the LightGBM native library integration. The fix was merged into master and included in published releases starting with mmlspark 0.19.0 and carried forward into SynapseML v1.1.3. If you encounter similar network errors on current releases, please open a new issue with updated logs.
